version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - PGDATA:/usr/mnt/database

volumes:
  PGDATA:
    driver: local
